version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
executors:
  chrome-ff:
    docker:
      - image 'cypress/browsers:node12.14.1-chrome85-ff81'
workflows:
  build:
    jobs:
      - cypress/run:
          name: Cypress:Api-copy
          executor: chrome-ff
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: 4 machines
          browser: chrome
          spec: "cypress/integration/api-copy"

      - cypress/run:
          name: Cypress:
          executor: chrome-ff
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: 4 machines
          browser: chrome
          spec: "cypress/integration/ui-copy"

      - cypress/run:
          name: Cypress:
          executor: chrome-ff
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: 4 machines
          browser: chrome
          spec: "cypress/integration/api,cypress/integration/api-request,cypress/integration/ui"
