version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          name: Cypress:Api-copy
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: Api-copy
          browser: chrome
          spec: "cypress/integration/api-copy"

      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          name: Cypress:UI-copy
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: UI-copy
          browser: chrome
          spec: "cypress/integration/ui-copy"

      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          name: Cypress:The-rest
          record: true
          store_artifacts: true
          command: npm run build:test
          parallel: true
          parallelism: 4
          group: The-rest
          browser: chrome
          spec: "cypress/integration/api,cypress/integration/api-request,cypress/integration/ui"
